#ifndef _protocol_h_
#define _protocol_h_

enum eMsg:unsigned short{
	MSG_RAW=10000,
	
	MSG_CG_BEGIN,
	//Client---------------- Gateway
	MSG_CG_LOGIN,
	MSG_GC_LOGIN,

	MSG_CG_END,
	MSG_CZ_BEGIN,
	//Client---------------- Zone
	MSG_CZ_ENTER,
	MSG_ZC_ENTER,
	MSG_CZ_CREATE_PLAYER,
	MSG_ZC_CREATE_PLAYER,
	MSG_CZ_UPDATE_PLAYER,
	MSG_ZC_UPDATE_PLAYER,
	MSG_CZ_REMOVE_PLAYER,
	MSG_ZC_REMOVE_PLAYER,
	MSG_CZ_GET_PLAYER_EXTRA,
	MSG_CZ_UPDATE_PLAYER_EXTRA,
	MSG_ZC_UPDATE_PLAYER_EXTRA,
	MSG_CZ_MOVE,
	MSG_ZC_MOVE,

	MSG_ZC_SYNC_PLAYERS,

	MSG_CZ_UPDATE_NAME,		//TEST
	MSG_ZC_UPDATE_NAME,

	MSG_CZ_ENTER_ARENA,
	MSG_ZC_ENTER_ARENA,

	MSG_CZ_END,
	MSG_CA_BEGIN,
	//Client---------------- Arena
	MSG_CA_ENTER,
	MSG_AC_ENTER,

	MSG_CA_END,
	MSG_ZG_BEGIN,
	//Zone	---------------- Gateway
	MSG_ZG_CONNECT,
	MSG_GZ_CONNECT,

	MSG_ZG_END,
	MSG_ZW_BEGIN,
	//Zone	---------------- World
	MSG_ZW_CONNECT,
	MSG_WZ_CONNECT,

	MSG_ZW_END,
	MSG_ZA_BEGIN,
	//Zone	---------------- Arena
	MSG_AZ_CONNECT,
	MSG_ZA_CONNECT,
	MSG_ZA_CLIENT_ENTER,
	MSG_AZ_CLIENT_ENTER,

	MSG_AZ_UPDATE_PLAYER,
	MSG_ZA_UPDATE_PLAYER,
	MSG_AZ_UPDATE_PLAYER_EXTRA,
	MSG_ZA_UPDATE_PLAYER_EXTRA,

	MSG_ZA_END,
};
#endif // _protocol_h_