NAME= keye
BUILDMODE=dynamic
CFLAGS+= -D_DEBUG -D_CRT_SECURE_NO_DEPRECATE
CFLAGS+= -I./ -I../ -I./htio/ -I./utility/threadpool/ -I$(DEPENDENCIES)/include
LDFLAGS+= -L$(DEPENDENCIES)/lib
LIBS+= -lm -lrt -lmysqlclient -lstdc++ -lboost_system -lboost_date_time -lboost_regex -lboost_thread -lboost_chrono
SRCS= $(wildcard allocator/*.cpp) \
	$(wildcard cache/*.cpp) \
	$(wildcard htio/*.cpp) \
	$(wildcard keyeio/*.cpp) \
	$(wildcard mysql_proxy/*.cpp) \
	$(wildcard utility/*.cpp) \
	$(wildcard *.cpp)
INCS= $(wildcard allocator/*.h) \
	$(wildcard cache/*.h) \
	$(wildcard htio/*.h) \
	$(wildcard htio/*.hpp) \
	$(wildcard htio/bas/*.hpp) \
	$(wildcard mysql_proxy/*.h) \
	$(wildcard mysql_proxy/*.hpp) \
	$(wildcard utility/*.h) \
	$(wildcard utility/*.hpp) \
	$(wildcard *.h) \
	$(wildcard *.hpp)
