version: "2"

services:
  data_volume:
    image: ubuntu:16.04
    volumes:
      - ./data:/var/data/

  redis:
    image: redis:3.2.0
    ports:
      - 6543:6543
      - 6379:6379
    volumes:
      - ./redis:/var/redis/
    volumes_from:
      - data_volume
    #command: redis-server /var/redis/redis.conf
    command: ls -lh /var/data

#  redis-cluster:
#    build: redis/
#    ports:
#      - 6543:6543
#      - 6379:6379
#    volumes:
#      - ./redis:/var/redis/

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/mysql/
    command: ls -lh /var/mysql

  nginx:
    image: nginx:1.10
    ports:
      - 80:80
    volumes:
      - ./nginx:/var/nginx/
    #command: nginx -c /etc/nginx/nginx.conf
    command: /bin/bash

  compiler:
    build: compiler/
    volumes_from:
      - data_volume
    command: ls -lh /var/data

  gitsvn:
    build: gitsvn/

  libs:
    build: libs/

#  develop:
#    build: develop/

#  server:
#    build: server/
#    volumes:
#      - ./server:/var/server
#    links:
#      - redis
#      - mysql
#    ports:
#      - 8200:8200

#  ha:
#    build: ha/
#    volumes:
#      - ./ha:/var/ha
