FROM centos:7
#FROM ubuntu:16.04
MAINTAINER Vic

#ADD epel.repo /etc/yum.repos.d/epel.repo
#yum clean all && yum update
RUN yum -y update
RUN yum -y install vim gdb

#RUN apt-get -y update
#RUN apt-get -y install vim subversion git
