FROM ubuntu:16.04
MAINTAINER Vic

RUN apt-get -y update
RUN apt-get -y install wget

#RUN wget http://www.haproxy.org/download/1.6/src/haproxy-1.6.5.tar.gz
#RUN make install
#RUN mkdir -p /usr/local/haproxy/etc
#RUN mkdir -p /usr/local/haproxy/sbin
#ADD ha/haproxy.cfg /usr/local/haproxy/etc
#RUN ln -s /usr/local/sbin/haproxy /usr/local/haproxy/sbin/haproxy 

#RUN tar zxvf keepalived-1.2.22.tar.gz
#WORKDIR keepalived-1.2.22
#RUN ./configure
#RUN make && make install
