FROM centos:7
MAINTAINER Vic

RUN yum -y update
#RUN yum -y upgrade
RUN yum -y install vim git svn
RUN yum -y install automake autoconf libtool make
RUN yum -y install gcc g++
RUN yum -y install openssl-devel openssh-server
